/**
 * Google Calendar Integration for TaskForce Tickets
 * Creates calendar events when cases are accepted
 */

import { google } from 'googleapis';

// Recipients for court date calendar invites
const CALENDAR_RECIPIENTS = [
  'will@302digitaladvisory.com',
  'cshaw0305@gmail.com',
  'developer@taskforcetickets.com',
];

interface CourtDateEvent {
  caseId: string;
  customerName: string;
  citationNumber: string;
  courtDate: string; // ISO date string
  courtTime?: string; // e.g., "9:00 AM"
  courtLocation?: string;
  courtJurisdiction?: string;
}

/**
 * Create a Google Calendar event for a court date
 */
export async function createCourtDateEvent(eventData: CourtDateEvent): Promise<{ success: boolean; eventId?: string; error?: string }> {
  try {
    // Initialize Google Auth with service account
    const auth = new google.auth.GoogleAuth({
      credentials: {
        client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
        private_key: process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
      },
      scopes: ['https://www.googleapis.com/auth/calendar'],
    });

    const calendar = google.calendar({ version: 'v3', auth });

    // Parse court date and time
    const courtDate = new Date(eventData.courtDate);
    let startDateTime: Date;
    let endDateTime: Date;

    if (eventData.courtTime) {
      // Parse time like "9:00 AM" or "14:00"
      const timeMatch = eventData.courtTime.match(/(\d{1,2}):?(\d{2})?\s*(AM|PM)?/i);
      if (timeMatch) {
        let hours = parseInt(timeMatch[1]);
        const minutes = parseInt(timeMatch[2] || '0');
        const period = timeMatch[3]?.toUpperCase();
        
        if (period === 'PM' && hours !== 12) hours += 12;
        if (period === 'AM' && hours === 12) hours = 0;
        
        startDateTime = new Date(courtDate);
        startDateTime.setHours(hours, minutes, 0, 0);
      } else {
        // Default to 9 AM if can't parse
        startDateTime = new Date(courtDate);
        startDateTime.setHours(9, 0, 0, 0);
      }
    } else {
      // Default to 9 AM
      startDateTime = new Date(courtDate);
      startDateTime.setHours(9, 0, 0, 0);
    }

    // Court appearances typically last 1-2 hours
    endDateTime = new Date(startDateTime);
    endDateTime.setHours(endDateTime.getHours() + 2);

    // Build location string
    const location = eventData.courtLocation || 
      (eventData.courtJurisdiction === 'Memphis' || eventData.courtJurisdiction === 'Shelby County' 
        ? '201 Poplar Ave, Memphis, TN 38103' 
        : eventData.courtJurisdiction || 'Memphis Traffic Court');

    // Create the event
    const event = {
      summary: `🚗 Court: ${eventData.customerName} - ${eventData.citationNumber || eventData.caseId}`,
      description: `TaskForce Tickets Case

Client: ${eventData.customerName}
Citation #: ${eventData.citationNumber || 'N/A'}
Case ID: ${eventData.caseId}
Jurisdiction: ${eventData.courtJurisdiction || 'Memphis'}

---
Auto-generated by TaskForce Tickets`,
      location: location,
      start: {
        dateTime: startDateTime.toISOString(),
        timeZone: 'America/Chicago',
      },
      end: {
        dateTime: endDateTime.toISOString(),
        timeZone: 'America/Chicago',
      },
      attendees: CALENDAR_RECIPIENTS.map(email => ({ email })),
      reminders: {
        useDefault: false,
        overrides: [
          { method: 'email', minutes: 24 * 60 }, // 1 day before
          { method: 'popup', minutes: 60 }, // 1 hour before
        ],
      },
      // Send notifications to attendees
      sendUpdates: 'all',
    };

    // Use the primary calendar of the service account
    // Note: Service account needs calendar access or use a shared calendar
    const response = await calendar.events.insert({
      calendarId: process.env.GOOGLE_CALENDAR_ID || 'primary',
      requestBody: event,
      sendUpdates: 'all',
    });

    console.log('Calendar event created:', response.data.id);

    return {
      success: true,
      eventId: response.data.id || undefined,
    };
  } catch (error) {
    console.error('Failed to create calendar event:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to create calendar event',
    };
  }
}

/**
 * Alternative: Send calendar invite via email (ICS file)
 * This works without Google Calendar API access
 */
export function generateICSContent(eventData: CourtDateEvent): string {
  const courtDate = new Date(eventData.courtDate);
  let startDateTime = new Date(courtDate);
  startDateTime.setHours(9, 0, 0, 0); // Default 9 AM
  
  if (eventData.courtTime) {
    const timeMatch = eventData.courtTime.match(/(\d{1,2}):?(\d{2})?\s*(AM|PM)?/i);
    if (timeMatch) {
      let hours = parseInt(timeMatch[1]);
      const minutes = parseInt(timeMatch[2] || '0');
      const period = timeMatch[3]?.toUpperCase();
      
      if (period === 'PM' && hours !== 12) hours += 12;
      if (period === 'AM' && hours === 12) hours = 0;
      
      startDateTime.setHours(hours, minutes, 0, 0);
    }
  }

  const endDateTime = new Date(startDateTime);
  endDateTime.setHours(endDateTime.getHours() + 2);

  const location = eventData.courtLocation || '201 Poplar Ave, Memphis, TN 38103';

  // Format dates for ICS (YYYYMMDDTHHmmssZ)
  const formatICSDate = (date: Date) => {
    return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  };

  const uid = `taskforce-${eventData.caseId}-${Date.now()}@taskforcetickets.com`;
  const now = formatICSDate(new Date());

  return `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//TaskForce Tickets//Court Date//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
UID:${uid}
DTSTAMP:${now}
DTSTART:${formatICSDate(startDateTime)}
DTEND:${formatICSDate(endDateTime)}
SUMMARY:🚗 Court: ${eventData.customerName} - ${eventData.citationNumber || eventData.caseId}
DESCRIPTION:TaskForce Tickets Case\\n\\nClient: ${eventData.customerName}\\nCitation #: ${eventData.citationNumber || 'N/A'}\\nCase ID: ${eventData.caseId}
LOCATION:${location}
STATUS:CONFIRMED
SEQUENCE:0
BEGIN:VALARM
TRIGGER:-P1D
ACTION:DISPLAY
DESCRIPTION:Court date tomorrow
END:VALARM
BEGIN:VALARM
TRIGGER:-PT1H
ACTION:DISPLAY
DESCRIPTION:Court date in 1 hour
END:VALARM
END:VEVENT
END:VCALENDAR`;
}

export { CALENDAR_RECIPIENTS };
